DELETE FROM shop_item;

INSERT INTO SHOP_ITEM (title, description, img_path, price, created_date, last_modified_date)
VALUES
    ('ITEM1', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent euismod leo leo, non lacinia felis consequat vel. Duis egestas sem non ex euismod, quis faucibus justo sagittis. In porttitor ante in ligula iaculis finibus. Suspendisse potenti. Donec eu faucibus velit, sit amet auctor ex. Sed orci ex, tincidunt at ligula ut, posuere semper diam.', 'item1.jpg', 10, '2025-03-04T07:17:33Z', '2025-03-04T07:17:33Z'),
    ('ITEM2', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent euismod leo leo, non lacinia felis consequat vel. Duis egestas sem non ex euismod, quis faucibus justo sagittis. In porttitor ante in ligula iaculis finibus. Suspendisse potenti. Donec eu faucibus velit, sit amet auctor ex. Sed orci ex, tincidunt at ligula ut, posuere semper diam.', 'item2.jpg', 20, '2025-03-04T07:17:33Z', '2025-03-04T07:17:33Z'),
    ('ITEM3', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent euismod leo leo, non lacinia felis consequat vel. Duis egestas sem non ex euismod, quis faucibus justo sagittis. In porttitor ante in ligula iaculis finibus. Suspendisse potenti. Donec eu faucibus velit, sit amet auctor ex. Sed orci ex, tincidunt at ligula ut, posuere semper diam.', 'item3.jpg', 30, '2025-03-04T07:17:33Z', '2025-03-04T07:17:33Z'),
    ('ITEM4', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent euismod leo leo, non lacinia felis consequat vel. Duis egestas sem non ex euismod, quis faucibus justo sagittis. In porttitor ante in ligula iaculis finibus. Suspendisse potenti. Donec eu faucibus velit, sit amet auctor ex. Sed orci ex, tincidunt at ligula ut, posuere semper diam.', 'item4.jpg', 500, '2025-03-04T07:17:33Z', '2025-03-04T07:17:33Z'),
    ('ITEM5', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent euismod leo leo, non lacinia felis consequat vel. Duis egestas sem non ex euismod, quis faucibus justo sagittis. In porttitor ante in ligula iaculis finibus. Suspendisse potenti. Donec eu faucibus velit, sit amet auctor ex. Sed orci ex, tincidunt at ligula ut, posuere semper diam.', 'item5.jpg', 300, '2025-03-04T07:17:33Z', '2025-03-04T07:17:33Z'),
    ('ITEM6', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent euismod leo leo, non lacinia felis consequat vel. Duis egestas sem non ex euismod, quis faucibus justo sagittis. In porttitor ante in ligula iaculis finibus. Suspendisse potenti. Donec eu faucibus velit, sit amet auctor ex. Sed orci ex, tincidunt at ligula ut, posuere semper diam.', 'item6.jpg', 200, '2025-03-04T07:17:33Z', '2025-03-04T07:17:33Z'),
    ('ITEM7', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent euismod leo leo, non lacinia felis consequat vel. Duis egestas sem non ex euismod, quis faucibus justo sagittis. In porttitor ante in ligula iaculis finibus. Suspendisse potenti. Donec eu faucibus velit, sit amet auctor ex. Sed orci ex, tincidunt at ligula ut, posuere semper diam.', 'item7.jpg', 100, '2025-03-04T07:17:33Z', '2025-03-04T07:17:33Z'),
    ('ITEM8', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent euismod leo leo, non lacinia felis consequat vel. Duis egestas sem non ex euismod, quis faucibus justo sagittis. In porttitor ante in ligula iaculis finibus. Suspendisse potenti. Donec eu faucibus velit, sit amet auctor ex. Sed orci ex, tincidunt at ligula ut, posuere semper diam.', 'item8.jpg', 400, '2025-03-04T07:17:33Z', '2025-03-04T07:17:33Z'),
    ('ITEM9', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent euismod leo leo, non lacinia felis consequat vel. Duis egestas sem non ex euismod, quis faucibus justo sagittis. In porttitor ante in ligula iaculis finibus. Suspendisse potenti. Donec eu faucibus velit, sit amet auctor ex. Sed orci ex, tincidunt at ligula ut, posuere semper diam.', 'item9.jpg', 40, '2025-03-04T07:17:33Z', '2025-03-04T07:17:33Z'),
    ('ITEM10', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent euismod leo leo, non lacinia felis consequat vel. Duis egestas sem non ex euismod, quis faucibus justo sagittis. In porttitor ante in ligula iaculis finibus. Suspendisse potenti. Donec eu faucibus velit, sit amet auctor ex. Sed orci ex, tincidunt at ligula ut, posuere semper diam.', 'item10.jpg', 70, '2025-03-04T07:17:33Z', '2025-03-04T07:17:33Z');
