--liquibase formatted sql

--changeset azmeev:1
CREATE TABLE SHOP_USER (
    ID bigint not null primary key generated by default as identity,
    USERNAME varchar(256) not null unique
);
--changeset azmeev:2
ALTER TABLE shop_cart_item ADD column USER_ID bigint not null references SHOP_USER(ID) default 0;

--changeset azmeev:3
ALTER TABLE shop_order ADD column USER_ID bigint not null references SHOP_USER(ID) default 0;
