--liquibase formatted sql

--changeset azmeev:1
CREATE TABLE PAYMENT_ACCOUNT (
    ID bigint not null primary key generated by default as identity,
    USERNAME varchar(256) not null unique,
    BALANCE numeric not null
);