spring:
  application:
    name: showcase-service
  r2dbc:
    url: ${R2DBC_DATASOURCE_URL:r2dbc:postgresql://localhost:5432/shop}
    username: ${DATASOURCE_USER:shop}
    password: ${DATASOURCE_PASSWORD:shop}
  liquibase:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shop}
    user: ${DATASOURCE_USER:shop}
    password: ${DATASOURCE_PASSWORD:shop}
  sql:
    init:
      mode: always
      data-locations: classpath:sql/data.sql
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
server:
  port: 8080

shop:
  defaultPageSize: 5
  defaultPageNumber: 1
  paymentUrl: ${PAYMENT_URL:http://localhost:8081}
