spring:
  application:
    name: showcase-service
  r2dbc:
    url: ${R2DBC_DATASOURCE_URL:r2dbc:postgresql://localhost:5432/shop}
    username: ${DATASOURCE_USER:shop}
    password: ${DATASOURCE_PASSWORD:shop}
  liquibase:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shop}
    user: ${DATASOURCE_USER:shop}
    password: ${DATASOURCE_PASSWORD:shop}
  sql:
    init:
      mode: always
      data-locations: classpath:sql/data.sql
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://${KEYCLOAK_URL:localhost:8099}/realms/master
        registration:
          keycloak:
            authorizationGrantType: authorization_code
            provider: keycloak
            client-id: showcase-service
            client-secret: ${CLIENT_SECRET:H8PKX4n0lFfDpPNQQyQjiBss9dT2DZuD}
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            scope: openid, profile, email
server:
  port: 8080

shop:
  clientRegistrationId: keycloak
  defaultPageSize: 5
  defaultPageNumber: 1
  paymentUrl: ${PAYMENT_URL:http://localhost:8081}
