/*
 * Payment Service API
 * Reactive RESTful API for payment operations
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.azmeev.intershop.showcase.web.dto.payment;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.Valid;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * PaymentResponse
 */
@JsonPropertyOrder({
        PaymentResponse.JSON_PROPERTY_SUCCESS,
        PaymentResponse.JSON_PROPERTY_REMAINING_BALANCE,
        PaymentResponse.JSON_PROPERTY_MESSAGE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-16T11:53:58.024048100+03:00[Europe/Moscow]", comments = "Generator version: 7.12.0")
public class PaymentResponse {
    public static final String JSON_PROPERTY_SUCCESS = "success";
    @jakarta.annotation.Nullable
    private Boolean success;

    public static final String JSON_PROPERTY_REMAINING_BALANCE = "remainingBalance";
    @jakarta.annotation.Nullable
    private BigDecimal remainingBalance;

    public static final String JSON_PROPERTY_MESSAGE = "message";
    @jakarta.annotation.Nullable
    private String message;

    public PaymentResponse() {
    }

    public PaymentResponse success(@jakarta.annotation.Nullable Boolean success) {
        this.success = success;
        return this;
    }

    /**
     * Payment status
     *
     * @return success
     */
    @jakarta.annotation.Nullable

    @JsonProperty(JSON_PROPERTY_SUCCESS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getSuccess() {
        return success;
    }


    @JsonProperty(JSON_PROPERTY_SUCCESS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSuccess(@jakarta.annotation.Nullable Boolean success) {
        this.success = success;
    }

    public PaymentResponse remainingBalance(@jakarta.annotation.Nullable BigDecimal remainingBalance) {
        this.remainingBalance = remainingBalance;
        return this;
    }

    /**
     * Remaining balance after payment
     *
     * @return remainingBalance
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_REMAINING_BALANCE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getRemainingBalance() {
        return remainingBalance;
    }


    @JsonProperty(JSON_PROPERTY_REMAINING_BALANCE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRemainingBalance(@jakarta.annotation.Nullable BigDecimal remainingBalance) {
        this.remainingBalance = remainingBalance;
    }

    public PaymentResponse message(@jakarta.annotation.Nullable String message) {
        this.message = message;
        return this;
    }

    /**
     * Additional information
     *
     * @return message
     */
    @jakarta.annotation.Nullable

    @JsonProperty(JSON_PROPERTY_MESSAGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getMessage() {
        return message;
    }


    @JsonProperty(JSON_PROPERTY_MESSAGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMessage(@jakarta.annotation.Nullable String message) {
        this.message = message;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PaymentResponse paymentResponse = (PaymentResponse) o;
        return Objects.equals(this.success, paymentResponse.success) &&
                Objects.equals(this.remainingBalance, paymentResponse.remainingBalance) &&
                Objects.equals(this.message, paymentResponse.message);
    }

    @Override
    public int hashCode() {
        return Objects.hash(success, remainingBalance, message);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PaymentResponse {\n");
        sb.append("    success: ").append(toIndentedString(success)).append("\n");
        sb.append("    remainingBalance: ").append(toIndentedString(remainingBalance)).append("\n");
        sb.append("    message: ").append(toIndentedString(message)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

