version: '3.3'

services:
  shop-web:
    restart: always
    build:
      dockerfile: ./Dockerfile
    container_name: shop-web
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:35432/shop
      R2DBC_DATASOURCE_URL: r2dbc:postgresql://host.docker.internal:35432/shop
    ports:
      - "${SHOP_PORT:-8080}:8080"
    depends_on:
      - shop-postgres
    networks:
      - shop

  shop-postgres:
    restart: always
    image: postgres:16.1
    container_name: shop-postgres
    environment:
      POSTGRES_USER: ${SHOP_DB_USERNAME:-shop}
      POSTGRES_PASSWORD: ${SHOP_DB_PASSWORD:-shop}
      POSTGRES_DB: ${SHOP_DB_NAME:-shop}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --data-checksums"
    volumes:
      - shop-volume-postgres:/var/lib/postgresql/data
    ports:
      - "35432:5432"
    networks:
      - shop

volumes:
  shop-volume-postgres:

networks:
  shop: